##
##                                           /$$
##                                          |__/
##      /$$$$$$  /$$$$$$/$$$$   /$$$$$$  /$$ /$$  /$$$$$$$
##     /$$__  $$| $$_  $$_  $$ /$$__  $$|__/| $$ /$$_____/
##    | $$$$$$$$| $$ \ $$ \ $$| $$  \ $$ /$$| $$|  $$$$$$
##    | $$_____/| $$ | $$ | $$| $$  | $$| $$| $$ \____  $$
##    |  $$$$$$$| $$ | $$ | $$|  $$$$$$/| $$| $$ /$$$$$$$/
##     \_______/|__/ |__/ |__/ \______/ | $$|__/|_______/
##          plugin by unnamed      /$$  | $$
##                                |  $$$$$$/
##                                 \______/
##

#
# Welcome to the emojis configuration!
#
#
#  -  If you want to use special characters in the config file, you need
#     to save the file using UTF-8, not ANSI or any other encoding
#
#
# If you need help with the configuration, feel free to contact us on
#  -    Discord: https://discord.gg/xbba2fy
#

format:

    # The text displayed when the player hovers an emoji
    # in a player message. Available placeholders:
    # - <emoji>: The Emoji character itself
    # - <emojiname>: The Emoji name
    hover:
        # Format to use when MiniMessage is supported by the server (Paper 1.18+)
        # If not specified, it uses the legacy ampersand formatting
        # mini-message: '<emoji> <gray>:<emojiname>: <#ff8df8>/emojis'

        # Format to use by default (Spigot, Paper 1.17 and olders)
        # Uses the legacy ampersand formatting
        legacy: '&f<emoji> &7:<emojiname>: &d/emojis'

    # Configuration for when not running on a Paper server
    legacy:
        # Initial message prefix, because we can't obtain it
        # from other plugins when using AsyncPlayerChatEvent
        message-prefix: '&f'

compat:
    # If enabled, the plugin will use the Paper API to listen
    # to chat messages. This will allow the plugin to use rich
    # components.
    #
    # Note: If enabled, the listener will be executed AFTER
    #  all the listeners registered for the legacy event,
    #  however, if other plugins use the modern event, the
    #  "listener-priority" setting is still available
    use-paper-listener: true

    # Specify the listener priority to use, LOW by default
    #
    # Available priorities:
    # - LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    #
    # If the listener-priority is lower, it will be executed
    # BEFORE other plugins' listeners, if it's higher, it will
    # be executed AFTER other plugins' listeners
    listener-priority: 'LOW'

# pack:
    # Which font should we use to write the emojis?
    #
    # You can use 'minecraft:default' so it uses the default
    # Minecraft font, or specify any other one to use a custom
    # one, like "myserver:emojifont"
    #
    # Using a custom font is recommended to avoid conflicts
    # (two or more plugins using the same font and the same
    # characters for different things), but it requires the
    # 'use-paper-listener' option to be set to true
#    font: 'minecraft:default'

messages:
    help: |-
        &8----------------- &dµŋemojis &8- &7Help Page &8-----------------
        &8 - &d/emojis update <id> &8- &7Import emojis from https://unnamed.team/emojis
        &8 - &d/emojis list [page] &8- &7List all emojis
        &8 - &d/emojis reload &8- &7Reload emojis from the emojis.mcemoji file
        &8-----------------------------------------------------
    list:
        invalid-page: '&cInvalid page number!'
        header: '&8&m                    &d µŋemojis &8- &7Page <page> / <maxpages> &8&m                    '
        element:
            available:
                content: '&f<emoji>'
                hover: '&f<emoji> &8:<emojiname>:'
            unavailable:
                content: '&7<emoji>'
                hover: |-
                    &cBuy VIP to unlock this emoji!
                      &7<emoji> &8:<emojiname>:
        show-unavailable: false
        separation:
            1: ' '    # every 1 emoji, add a space
            28: "\n"  # every 28 emojis, add a new line
        max-emojis-per-page: 84
        footer: '&8&m                                                                       '